#! /bin/sh
# /etc/init.d/HeaterControlBack
#

# Source function library.
#. /etc/init.d/functions

case "$1" in
    start)
       python3 @FOLDER@/main.py 1>>/home/pi/HeaterControl.log 2>>/home/pi/HeaterControl.err
       ;;
    stop)
       echo "stop"
       pid=`ps ax | grep 'HeaterControl/main.py' | head -n1 | awk '{ print $1 }'`
       echo $pid
       kill $pid
       sleep 2
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
