#! /bin/sh
# /etc/init.d/HeaterControlCron
#

# Source function library.
#. /etc/init.d/functions

case "$1" in 
    start)
       python3 @FOLDER@/webRest.py
       ;;
    stop)
       echo "stop"
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 